version: '3'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    logging:
        driver: none
    volumes:
      - mongo_data:/data/db

  collector:
    build: ./collector
    volumes:
      - ./collector/app/:/app/
      - ./collector/config/conig.json:/app/config/
    environment:
      - DEBUG=true
      - TRANSMITTER_HOST=core
      - TRANSMITTER_PORT=514
      - SYSLOG=true
      - SYSLOG_PORT=514
    ports:
      - "514:514"       

  core:
    build: ./core
    volumes:
      - ./core/app/:/app/
      # - ./core/app/config/:/app/config
    environment:
      - DATABASE_URI=mongodb://root:root@mongo:27017/
      - DEBUG=true
    depends_on:
       - mongo

  backend:
    build: ./web/backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir app/ --forwarded-allow-ips=*
    volumes:
      - ./web/backend/:/app/
      - ./core/config/:/app/config
    environment:
      - DATABASE_URI=mongodb://root:root@mongo:27017/
      - OPENAI_API_KEY=
    depends_on:
       - mongo

  frontend:
    build: ./web/frontend
    volumes:
      #- ./web/frontend/dist:/app/dist
      - ./web/frontend/app:/app
      #- ./core/config/:/app/config
    environment:
      CHOKIDAR_USEPOLLING: 1    
      WDS_SOCKET_PORT: 443
      REACT_APP_URL: localhost
    depends_on:
       - mongo

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      #- ./web/frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/server.crt:/etc/ssl/certs/server.crt
      - ./ssl/server.key:/etc/ssl/private/server.key
    depends_on:
      - frontend
      - backend
    logging:
        driver: none
        
volumes:
  mongo_data: